server:
  port: 8000

spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mariadb://localhost:33306/security_study?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
  config:
    activate:
      on-profile: local
jwt:
  header: Authorization
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouwrutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  access-token-validity-in-seconds: 3600 # 10 min

# ?? ?? ?? ??? ??? ?? ????? ?? ????
#logging:
#  level:
#    org:
#      springframework.jdbc.core: trace
#      hibernate:
#        type: trace
